# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master 

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '7f87f6a6-51a6-40c9-bb58-bb6307a2237c'
  
  # Web app name
  webAppName: 'azurepipelinewindowsapp'

  # Environment name
  environmentName: 'azurepipelinewindowsapp'
  
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWindowsWebApp
    displayName: Deploy Windows Web App
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: Azurepipelinewapp3355'
            inputs:
              azureSubscription: 'Visual Studio Enterprise – MPN (fcf25602-06c2-4edc-b903-5b3c8099c1ee)'
              appType: 'webApp'
              appName: 'azurepipelinewindowsapp'
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
              deploymentMethod: 'auto'
